import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono, Pixelify_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Particles from "@/components/Particles/Particles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-mono',
});

const pixelify = Pixelify_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: '--font-pixelify-sans',

})

export const metadata: Metadata = {
  title: "Delwin Prakash - Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/logo/d.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo/dp.jpg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} ${pixelify.variable} antialiased bg-background text-foreground selection:bg-primary/30 min-h-screen flex flex-col`}
      >
        <div className="fixed inset-0 z-0 pointer-events-none opacity-40">
          <Particles
            particleColors={['#40ffaa', '#4079ff']}
            particleCount={150}
            particleSpread={10}
            speed={0.2}
            particleBaseSize={100}
            moveParticlesOnHover={true}
            alphaParticles={false}
            disableRotation={false}
          />
        </div>

        <div className="fixed top-0 left-0 right-0 z-50 pointer-events-none">
          <Navbar />
        </div>

        <main className="flex-grow relative z-10">
          {children}
        </main>

        <div className="relative z-10">
          <Footer />
        </div>
      </body>
    </html>
  );
}
