import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Mono, Pixelify_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-mono',
});

const pixelify = Pixelify_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: '--font-pixelify-sans',

})

export const metadata: Metadata = {
  title: "Delwin Prakash - Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: '/logo/d.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logo/d.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${spaceMono.variable} ${pixelify.variable} antialiased`}
      >
        <div className="absolute inset-x-0 top-0 z-50 pointer-events-none">
            <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
